name: PR Checks (Unit & E2E Tests)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check Formatting
        run: cargo fmt --all --check

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libudev-dev

      - name: Run Unit Tests
        run: cargo test --bins

      - name: Run E2E Tests
        run: cargo test --test e2e
